# Generated by Django 5.2.8 on 2025-11-09 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_id'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoupon',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
