# Generated by Django 5.2.8 on 2025-11-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_usercoupon_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercoupon',
            old_name='order_id',
            new_name='order',
        ),
    ]
