# Generated by Django 5.2.8 on 2025-11-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
